// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ResumeParserService.Context;

namespace ResumeParserService.Migrations
{
    [DbContext(typeof(AppDBContext))]
    [Migration("20220922153121_ADDCRTRACKERS")]
    partial class ADDCRTRACKERS
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.29")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ResumeParserService.Entities.CandidateDetail", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CandidateName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EmailID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MobileNumber")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("CandidateDetails");
                });

            modelBuilder.Entity("ResumeParserService.Entities.CandidateResumeTracker", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("CandidateDetailID")
                        .HasColumnType("int");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CreatedOn")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ModifiedOn")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ResumeStatusID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("CandidateDetailID");

                    b.HasIndex("ResumeStatusID");

                    b.ToTable("CandidateResumeTrackers");
                });

            modelBuilder.Entity("ResumeParserService.Entities.ResumeSave", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("CandidateDetailID")
                        .HasColumnType("int");

                    b.Property<string>("ResumePath")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.HasIndex("CandidateDetailID");

                    b.ToTable("ResumeSaves");
                });

            modelBuilder.Entity("ResumeParserService.Entities.ResumeStatus", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("StatusCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StatusName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("ResumeStatuses");
                });

            modelBuilder.Entity("ResumeParserService.Entities.CandidateResumeTracker", b =>
                {
                    b.HasOne("ResumeParserService.Entities.CandidateDetail", "CandidateDetail")
                        .WithMany()
                        .HasForeignKey("CandidateDetailID");

                    b.HasOne("ResumeParserService.Entities.ResumeStatus", "ResumeStatus")
                        .WithMany()
                        .HasForeignKey("ResumeStatusID");
                });

            modelBuilder.Entity("ResumeParserService.Entities.ResumeSave", b =>
                {
                    b.HasOne("ResumeParserService.Entities.CandidateDetail", "CandidateDetail")
                        .WithMany()
                        .HasForeignKey("CandidateDetailID");
                });
#pragma warning restore 612, 618
        }
    }
}
